{
    'name': 'Social Hub',
    'summary': 'Manage social media platforms, accounts and streams without IAP credits',
    'version': '19.0.4.0.0',
    'category': 'Marketing',
    'author': 'mamingxing',
    'company': 'iMyTest',
    'license': 'LGPL-3',
    'depends': ['base', 'mail'],
    'data': [
        'security/social_hub_security.xml',
        'security/ir.model.access.csv',
        'data/social_hub_platform_data.xml',
        'data/ir_cron_data.xml',
        'views/social_hub_menu_views.xml',
        'views/social_hub_platform_views.xml',
        'views/social_hub_account_views.xml',
        'views/social_hub_post_views.xml',
        'views/social_hub_stream_views.xml',
        'views/res_config_settings_views.xml',
    ],
    'application': True,
    'installable': True,
}
